import groovy.json.JsonOutput
import groovy.json.JsonSlurper

plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}

def secrets = new Properties()
def secretsFile = file('secrets.properties')
if (secretsFile.exists()) {
    secretsFile.withInputStream {
        stream -> secrets.load(stream)
    }

    fileTree("secrets").matching {
        include "**/*.properties"
    }.each {
        File file ->
            file.withInputStream {
                stream -> secrets.load(stream)
            }
    }
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

version = project.mod_version
group = "com.gizmo.tomes"

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-Xlint:all,-classfile,-processing,-deprecation,-this-escape" << "-Werror"
    options.encoding = 'UTF-8'
}

base {
    archivesName = project.modid+'-'+project.minecraft_version
}

neoForge {
    version = project.neo_version
    validateAccessTransformers = true

    mods {
        "${project.modid}" {
            it.sourceSet this.sourceSets.main
        }
    }

    runs {
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
        }

        client {
            client()
            if (secrets.getProperty("uuid")) {
                programArguments.addAll(
                    '--username', secrets.getProperty("username"),
                    '--uuid', secrets.getProperty("uuid"),
                    '--accessToken', "",
                    '--xuid', ""
                )
            }
        }

		data {
			data()
			programArguments.addAll(
				'--mod', modid,
				'--all',
				'--output', file('src/generated/resources/').getAbsolutePath(),
				'--existing', file('src/main/resources/').getAbsolutePath()
			)
		}

        server {
            server()
            programArgument '--nogui'
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
	maven {
		name 'Jared\'s Maven' // JEI
		url 'https://maven.blamejared.com/'
	}
	maven {
		name 'Shedaniel\'s Maven' //REI
		url "https://maven.shedaniel.me"
	}
	maven {
		name "TerraformersMC" //EMI
		url "https://maven.terraformersmc.com/"
	}
	maven {
		name 'Curseforge Maven'
		url "https://www.cursemaven.com"
		content {
			includeGroup "curse.maven"
		}
	}
}

dependencies {
	//make sure to only pick one of these when testing (switch others to compileOnly)
	implementation "mezz.jei:jei-${project.minecraft_version}-neoforge:${project.jei_version}"
//	compileOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${project.rei_version}"
	compileOnly "dev.emi:emi-neoforge:${project.emi_version}+${project.minecraft_version}"

	implementation "curse.maven:advanced-core-info-1661923:8759953"
	implementation "curse.maven:advanced-loot-info-1205426:8759960"
}

processResources {
    def ver = project.version
    filesMatching("META-INF/neoforge.mods.toml") {
        expand([
            'file': [
                'jarVersion': ver
            ]
        ])
    }
    def lazyTree = providers.provider {
        fileTree(dir: getOutputs().getFiles().getAsPath(), includes: ["**/*.json", "**/*.mcmeta"])
    }
    doLast {
        lazyTree.get().each {
            File file -> file.setText(JsonOutput.toJson(new JsonSlurper().parse(file)))
        }
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                "Specification-Title"     : "${project.modid}",
                "Specification-Vendor"    : "GizmoTheMoonPig",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "GizmoTheMoonPig",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}
